services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Xz13467980@
      MYSQL_DATABASE: watnow_spring_project2025_backend_development
      # MYSQL_USER: root
      MYSQL_PASSWORD: Xz13467980@
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env.production
    volumes:
      - .:/rails
      - bundle_data:/usr/local/bundle
    #railway使用時はコメントアウトしてください
    # depends_on:
    #   - db
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0 -p 3000"

volumes:
  db_data:
  bundle_data:
