---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/gyms":
    get:
      summary: ジム一覧を取得
      tags:
      - Gyms
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
    post:
      summary: ジムを登録
      tags:
      - Gyms
      parameters: []
      responses:
        '201':
          description: ok
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                gym:
                  type: object
                  properties:
                    name:
                      type: string
                    location:
                      type: string
                    url:
                      type: string
                  required:
                  - name
              required:
              - gym
  "/gyms/{id}":
    delete:
      summary: ジムを削除
      tags:
      - Gyms
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '204':
          description: ok
  "/machines":
    get:
      summary: 機械一覧を取得
      tags:
      - Machines
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
    post:
      summary: 機械を登録
      tags:
      - Machines
      parameters: []
      responses:
        '201':
          description: created
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                machine:
                  type: object
                  properties:
                    name:
                      type: string
                    model:
                      type: string
                  required:
                  - name
                  - model
              required:
              - machine
  "/machines/{id}":
    delete:
      summary: 機械を削除
      tags:
      - Machines
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '204':
          description: deleted
  "/menus":
    get:
      summary: メニュー一覧を取得
      tags:
      - Menus
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
    post:
      summary: メニューを作成
      tags:
      - Menus
      parameters: []
      responses:
        '201':
          description: ok
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                menu:
                  type: object
                  properties:
                    name:
                      type: string
                    machine_id:
                      type: integer
                    part:
                      type: string
                    count:
                      type: integer
                    set_count:
                      type: integer
                    time:
                      type: integer
                    weight:
                      type: number
                  required:
                  - name
                  - machine_id
                  - part
              required:
              - menu
  "/menus/{id}":
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: string
    get:
      summary: 特定のメニューを取得
      tags:
      - Menus
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: object
        '404':
          description: not found
    put:
      summary: メニューを更新
      tags:
      - Menus
      parameters: []
      responses:
        '200':
          description: ok
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                menu:
                  type: object
                  properties:
                    name:
                      type: string
                    weight:
                      type: number
    delete:
      summary: メニューを削除
      tags:
      - Menus
      responses:
        '204':
          description: ok
  "/users":
    get:
      summary: ユーザー一覧を取得
      tags:
      - Users
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
    post:
      summary: ユーザー登録
      tags:
      - Users
      parameters: []
      responses:
        '201':
          description: ok
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    name:
                      type: string
                    email:
                      type: string
                    password:
                      type: string
                  required:
                  - name
                  - email
                  - password
              required:
              - user
  "/users/{id}":
    delete:
      summary: ユーザー削除
      tags:
      - Users
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '204':
          description: ok
servers:
- url: http://localhost:3000/api/v1
  description: Local development server
