---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/users":
    get:
      summary: ユーザー一覧を取得
      tags:
      - Users
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
