---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/users":
    get:
      summary: ユーザー一覧を取得
      tags:
      - Users
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
    post:
      summary: ユーザー登録
      tags:
      - Users
      parameters: []
      responses:
        '201':
          description: 作成成功
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    name:
                      type: string
                    email:
                      type: string
                    password:
                      type: string
                  required:
                  - name
                  - email
                  - password
              required:
              - user
  "/users/{id}":
    delete:
      summary: ユーザー削除
      tags:
      - Users
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '204':
          description: 削除成功
servers:
- url: http://localhost:3000/api/v1
  description: Local development server
